CREATE TABLE VENTANILLA.MENSAJE
(
    ID VARCHAR(64),
    DESTINATARIOS VARCHAR(512),
    MSG VARCHAR(4096),
    ADJUNTOS BLOB
);

CREATE TABLE VENTANILLA.PARAMETROS
(
    NOMBRE VARCHAR (128),
    VALOR VARCHAR  (4096)
);

